services:
  - type: web
    name: image-processor-api
    env: python
    region: frankfurt  # اختر Frankfurt لأنه أقرب للشرق الأوسط
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
    plan: free